import { useEffect, useRef, useState } from "react";

import { controlFixtures } from "../shared/control-fixtures";
import { decisionsForState, productionVisibilityForProject, projectById, summarizeDashboard, type ControlDashboardData, type DecisionReadModel, type ProjectReadModel } from "../shared/control-model";
import { classifyDashboardFreshness } from "../shared/dashboard-freshness";
import type { HealthPayload } from "../shared/health";
import { ActionConfirmationDialog } from "./components/ActionConfirmationDialog";
import { DecisionCard } from "./components/DecisionCard";
import { StatusPill } from "./components/StatusPill";
import { SystemHealthCard } from "./components/SystemHealthCard";
import { decisionActionErrorMessage, postDecisionAction, type DecisionActionTarget, type MutatingDecisionAction } from "./decision-action-client";
import { operatorAttentionForSummary } from "./operator-attention";
import { ControlReadError, isAbortedControlRead, readControlJson, type ControlReadFailureCode } from "./read-only-fetch";

type LiveDashboardState = "LOADING" | "LIVE" | "REFRESHING" | "DISABLED" | "STALE" | "FUTURE" | "INVALID" | "ERROR";
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function isHealthPayload(value: unknown): value is HealthPayload { return isRecord(value)&&value.status==="ok"&&value.service==="rozkalns-control"&&value.phase==="phase-0"&&(value.workerVersion===null||typeof value.workerVersion==="string"); }
function isControlDashboardData(value: unknown): value is ControlDashboardData {
  if (!isRecord(value) || typeof value.generatedAt !== "string" || !Array.isArray(value.projects) || !Array.isArray(value.decisions) || !Array.isArray(value.productionVisibility)) return false;
  const projectsValid = value.projects.every((project) => isRecord(project) && typeof project.id === "string" && typeof project.displayName === "string" && typeof project.repository === "string" && typeof project.enabled === "boolean" && (project.productionAdapter === "none" || project.productionAdapter === "rpi5") && (project.status === "HEALTHY" || project.status === "ATTENTION" || project.status === "WAITING") && Number.isSafeInteger(project.openPullRequests) && Number.isSafeInteger(project.openIssues));
  if (!projectsValid) return false;
  const validWorkflowStates=new Set(["NEEDS_ANDRIS","WORKING","WAITING","CI_FAILED","MERGE_READY","DONE"]); const validCiStates=new Set(["PASS","FAIL","RUNNING","WAITING"]); const validReviewStates=new Set(["PASS","CHANGES_REQUESTED","PENDING","NOT_REQUIRED"]); const validDeployImpacts=new Set(["NO_DEPLOY","AUTO_DEPLOY_SAFE","MANUAL_ROLLOUT_REQUIRED","DB_HOST_APPLY_REQUIRED","UNKNOWN"]); const validActions=new Set(["MERGE","NEEDS_CHANGES","LATER","OPEN_PR"]); const validRuntime=new Set(["HEALTHY","DEGRADED","UNREACHABLE","UNKNOWN"]); const validHealth=new Set(["PASS","FAIL","UNKNOWN"]); const validRollback=new Set(["AVAILABLE","UNAVAILABLE","UNKNOWN"]); const validDrift=new Set(["IN_SYNC","DRIFTED"]);
  const decisionsValid = value.decisions.every((decision) => { if(!isRecord(decision))return false; return typeof decision.id==="string"&&typeof decision.projectId==="string"&&validWorkflowStates.has(String(decision.workflowState))&&(decision.issueNumber===null||Number.isSafeInteger(decision.issueNumber))&&(decision.issueTitle===null||typeof decision.issueTitle==="string")&&(decision.prNumber===null||Number.isSafeInteger(decision.prNumber))&&(decision.prTitle===null||typeof decision.prTitle==="string")&&(decision.prUrl===undefined||decision.prUrl===null||typeof decision.prUrl==="string")&&validCiStates.has(String(decision.ci))&&validReviewStates.has(String(decision.review))&&validDeployImpacts.has(String(decision.deployImpact))&&Number.isSafeInteger(decision.changedFiles)&&(decision.expectedHeadSha===null||typeof decision.expectedHeadSha==="string")&&(decision.currentHeadSha===null||typeof decision.currentHeadSha==="string")&&typeof decision.mainSha==="string"&&typeof decision.reason==="string"&&typeof decision.lastReconciledAt==="string"&&Array.isArray(decision.allowedActions)&&decision.allowedActions.every((action)=>validActions.has(String(action))); });
  if (!decisionsValid) return false;
  return value.productionVisibility.every((item)=>isRecord(item)&&typeof item.projectId==="string"&&typeof item.repository==="string"&&typeof item.mainSha==="string"&&typeof item.productionSha==="string"&&validDeployImpacts.has(String(item.deployImpact))&&validRuntime.has(String(item.runtime))&&validHealth.has(String(item.health))&&validRollback.has(String(item.rollback))&&Array.isArray(item.blockerCodes)&&item.blockerCodes.every((code)=>typeof code==="string")&&typeof item.observedAt==="string"&&item.productionAdapter==="rpi5"&&validDrift.has(String(item.drift)));
}
function projectTone(status: ProjectReadModel["status"]) { if(status==="HEALTHY")return "good" as const; if(status==="ATTENTION")return "warning" as const; return "info" as const; }
function productionTone(drift:"IN_SYNC"|"DRIFTED"){return drift==="IN_SYNC"?"good" as const:"warning" as const;}
function shortSha(sha:string){return sha.slice(0,7);}
function snapshotTimestamp(timestamp:string){const parsed=new Date(timestamp);return Number.isFinite(parsed.getTime())?new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"UTC"}).format(parsed):"invalid timestamp";}
function liveReadFailureMessage(failure:ControlReadFailureCode|null,snapshotLabel:string|null){const retained=snapshotLabel?` · keeping ${snapshotLabel}`:" · fixture data shown";if(failure==="TIMEOUT")return `Live read timed out${retained}`;if(failure==="NETWORK")return `Network unavailable${retained}`;if(failure==="SERVER")return `Live service error${retained}`;if(failure==="INVALID_JSON"||failure==="INVALID_SCHEMA")return `Live data failed validation${retained}`;return `Live data unavailable${retained}`;}
function actionStartedNotice(action:MutatingDecisionAction){if(action==="MERGE")return "Sending confirmed squash-merge request";if(action==="NEEDS_CHANGES")return "Sending confirmed needs-changes request";return "Sending confirmed Later request";}
function actionCompletedNotice(action:MutatingDecisionAction){if(action==="MERGE")return "Merge request completed · refreshing canonical GitHub state";if(action==="NEEDS_CHANGES")return "Needs-changes request completed · refreshing canonical GitHub state";return "Later request completed · refreshing canonical GitHub state";}

export default function App(){
 const[health,setHealth]=useState<HealthPayload|null>(null);const[unavailable,setUnavailable]=useState(false);const[liveDashboard,setLiveDashboard]=useState<ControlDashboardData|null>(null);const[liveState,setLiveState]=useState<LiveDashboardState>("LOADING");const[liveFailure,setLiveFailure]=useState<ControlReadFailureCode|null>(null);const[refreshSequence,setRefreshSequence]=useState(0);const[notice,setNotice]=useState("Decision actions require fresh live state and explicit confirmation");const[pendingAction,setPendingAction]=useState<DecisionActionTarget|null>(null);const[actionInFlight,setActionInFlight]=useState(false);const actionLockRef=useRef(false);
 useEffect(()=>{const controller=new AbortController();void readControlJson("/api/health",{signal:controller.signal,validate:isHealthPayload}).then((payload)=>{setHealth(payload);setUnavailable(false);}).catch((error:unknown)=>{if(isAbortedControlRead(error))return;setUnavailable(true);});return()=>controller.abort();},[refreshSequence]);
 useEffect(()=>{const controller=new AbortController();let ignore=false;void readControlJson("/api/github/dashboard",{signal:controller.signal,validate:isControlDashboardData}).then((payload)=>{if(ignore)return;const freshness=classifyDashboardFreshness(payload);setLiveDashboard(payload);setLiveFailure(null);setLiveState(freshness.state==="FRESH"?"LIVE":freshness.state);}).catch((error:unknown)=>{if(isAbortedControlRead(error)||ignore)return;if(error instanceof ControlReadError&&error.status===503&&isRecord(error.payload)&&error.payload.error==="LIVE_READ_DISABLED"){setLiveDashboard(null);setLiveFailure(null);setLiveState("DISABLED");return;}setLiveFailure(error instanceof ControlReadError?error.code:"NETWORK");setLiveState("ERROR");});return()=>{ignore=true;controller.abort();};},[refreshSequence]);
 useEffect(()=>{if(liveState!=="LIVE"&&!actionLockRef.current)setPendingAction(null);},[liveState]);
 const dashboardSource=liveDashboard??controlFixtures;const dashboard=liveState==="LIVE"?dashboardSource:{...dashboardSource,decisions:dashboardSource.decisions.map((decision)=>({...decision,allowedActions:decision.allowedActions.filter((action)=>action==="OPEN_PR")}))};const live=liveDashboard!==null;const refreshInFlight=liveState==="LOADING"||liveState==="REFRESHING";const summary=summarizeDashboard(dashboard);const attention=operatorAttentionForSummary(summary);const needsAndris=decisionsForState(dashboard,"NEEDS_ANDRIS");const workingOrWaiting=decisionsForState(dashboard,"WORKING","WAITING");const ciFailed=decisionsForState(dashboard,"CI_FAILED");const mergeReady=decisionsForState(dashboard,"MERGE_READY");
 function refreshLiveDashboard(force=false){if(!force&&(refreshInFlight||actionInFlight))return;setPendingAction(null);setLiveFailure(null);setLiveState(liveDashboard?"REFRESHING":"LOADING");setRefreshSequence((value)=>value+1);}
 function openDecisionAction(action:MutatingDecisionAction,item:DecisionReadModel,project:ProjectReadModel){if(liveState!=="LIVE"||actionLockRef.current||actionInFlight)return;if(!item.allowedActions.includes(action))return;setPendingAction({action,item,project});setNotice(`${action==="MERGE"?"Squash merge":action==="NEEDS_CHANGES"?"Needs changes":"Later"} requires confirmation`);}
 function cancelDecisionAction(){if(actionLockRef.current||actionInFlight)return;setPendingAction(null);setNotice("Action cancelled · no request sent");}
 async function confirmDecisionAction(reviewBody:string){const target=pendingAction;if(!target||liveState!=="LIVE"||actionLockRef.current||actionInFlight)return;actionLockRef.current=true;setActionInFlight(true);setNotice(actionStartedNotice(target.action));try{await postDecisionAction(target,{reviewBody});setNotice(actionCompletedNotice(target.action));}catch(error:unknown){setNotice(`${decisionActionErrorMessage(error)} · refreshing canonical GitHub state`);}finally{actionLockRef.current=false;setActionInFlight(false);setPendingAction(null);refreshLiveDashboard(true);}}
 const workerLabel=health?.status==="ok"&&!unavailable?"Worker ready":unavailable?"Worker unavailable":"Worker checking";const snapshotLabel=liveDashboard?`Snapshot ${snapshotTimestamp(liveDashboard.generatedAt)} UTC`:null;const modeLabel=!live?"FIXTURE MODE":liveState==="LIVE"?"LIVE CONTROL":liveState==="FUTURE"?"LIVE · FUTURE":liveState==="INVALID"?"LIVE · INVALID":liveState==="REFRESHING"?"LIVE · REFRESHING":"LIVE · STALE";const modeStatus=liveState==="REFRESHING"&&snapshotLabel?`Refreshing live GitHub data · ${snapshotLabel}`:liveState==="STALE"?"Snapshot is over the five-minute freshness limit · last-known evidence only":liveState==="FUTURE"?"Snapshot exceeds the 30-second clock-skew allowance · last-known evidence only":liveState==="INVALID"?"Snapshot timestamp is invalid · last-known evidence only":liveState==="ERROR"?liveReadFailureMessage(liveFailure,snapshotLabel):live&&snapshotLabel?snapshotLabel:liveState==="LOADING"?"Checking live GitHub data":"Fixture mode";
 const renderDecision=(item:DecisionReadModel)=><DecisionCard key={item.id} item={item} project={projectById(dashboard,item.projectId)} onAction={openDecisionAction} mutationsLocked={actionInFlight}/>;
 return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to main content</a><header className="topbar"><div className="brand-mark" aria-hidden="true">RC</div><div className="brand-copy"><p>Rozkalns Control</p><span>Decision control</span></div><StatusPill label={modeLabel} tone={live&&liveState!=="LIVE"?"warning":"info"}/></header><main id="main-content" className="dashboard">
 <section className="hero" aria-labelledby="page-title"><div><p className="eyebrow">{live?"Daily MVP · Authenticated decision control":"Daily MVP · Safe fallback"}</p><h1 id="page-title">Current repository control state</h1><p className="summary">{live?"Mutating buttons appear only on fresh live decision state, require explicit confirmation, and are revalidated server-side before any write. Merge never authorizes deployment.":"Needs Andris is reserved for genuine owner-action gates. Fixture fallback has no live mutation authority."}</p></div></section>
 <div className="control-status-strip" role="status" aria-live="polite"><span className="control-status-strip__health"><span className="system-dot" aria-hidden="true"/>{workerLabel}</span><span className="control-status-strip__separator" aria-hidden="true">·</span><span>{modeStatus}</span><span className="control-status-strip__separator" aria-hidden="true">·</span><span className="control-status-strip__notice">{notice}</span><button className="control-status-strip__refresh" type="button" onClick={()=>refreshLiveDashboard()} disabled={refreshInFlight||actionInFlight} aria-label="Refresh live GitHub state" aria-busy={liveState==="REFRESHING"}>{liveState==="REFRESHING"?"Refreshing…":"Refresh"}</button></div>
 <section className="summary-strip" aria-label="Control summary"><div className="summary-metric summary-metric--attention"><span>{summary.needsAndris}</span><p>Needs Andris</p></div><div className="summary-metric"><span>{summary.workingOrWaiting}</span><p>Working / waiting</p></div><div className="summary-metric summary-metric--danger"><span>{summary.ciFailed}</span><p>CI failed</p></div><div className="summary-metric"><span>{summary.enabledProjects}</span><p>Projects</p></div></section>
 <section className={`operator-attention operator-attention--${attention.tone}`} aria-label="Operator attention"><div><p className="operator-attention__kicker">What needs attention now</p><h2>{attention.headline}</h2><p>{attention.detail}</p></div>{attention.target&&attention.actionLabel?<a className="operator-attention__action" href={attention.target}>{attention.actionLabel}</a>:null}</section>
 <SystemHealthCard refreshSequence={refreshSequence}/>
 <section id="needs-andris" className="dashboard-section dashboard-section--primary" aria-labelledby="needs-title"><div className="section-heading"><div><p className="eyebrow">Human gate</p><h2 id="needs-title">Needs Andris</h2></div><span className="section-count">{needsAndris.length}</span></div>{needsAndris.length>0?<div className="decision-list">{needsAndris.map(renderDecision)}</div>:<p className="section-empty-state">No owner action is required right now.</p>}</section>
 {workingOrWaiting.length>0?<section className="dashboard-section" aria-labelledby="active-title"><div className="section-heading"><div><p className="eyebrow">No action needed</p><h2 id="active-title">Working / Waiting</h2></div><span className="section-count">{workingOrWaiting.length}</span></div><div className="decision-list decision-list--compact">{workingOrWaiting.map(renderDecision)}</div></section>:null}
 {ciFailed.length>0?<section id="ci-failed" className="dashboard-section" aria-labelledby="failed-title"><div className="section-heading"><div><p className="eyebrow">Blocked</p><h2 id="failed-title">CI Failed</h2></div><span className="section-count section-count--danger">{ciFailed.length}</span></div><div className="decision-list decision-list--compact">{ciFailed.map(renderDecision)}</div></section>:null}
 {mergeReady.length>0?<section className="dashboard-section" aria-labelledby="ready-title"><div className="section-heading"><div><p className="eyebrow">Visible, not selected</p><h2 id="ready-title">Merge Ready</h2></div><span className="section-count">{mergeReady.length}</span></div><div className="decision-list decision-list--compact">{mergeReady.map(renderDecision)}</div></section>:null}
 <section className="dashboard-section" aria-labelledby="projects-title"><div className="section-heading"><div><p className="eyebrow">Configured scope</p><h2 id="projects-title">Projects</h2></div><span className="section-count">{summary.enabledProjects}</span></div><div className="project-grid">{dashboard.projects.map((project)=>{const production=productionVisibilityForProject(dashboard,project.id);return <article className="project-card" key={project.id}><div className="project-card__header"><div><h3>{project.displayName}</h3><p>{project.repository}</p></div><StatusPill label={project.status} tone={projectTone(project.status)}/></div><dl className="project-card__stats"><div><dt>PRs</dt><dd>{project.openPullRequests}</dd></div><div><dt>Issues</dt><dd>{project.openIssues}</dd></div><div><dt>Production</dt><dd>{project.productionAdapter==="rpi5"?"RPi5":"None"}</dd></div></dl>{project.productionAdapter==="rpi5"?<div className="project-card__production"><div className="project-card__header"><strong>Production visibility</strong>{production?<StatusPill label={production.drift} tone={productionTone(production.drift)}/>:<StatusPill label="UNAVAILABLE" tone="info"/>}</div>{production?<dl className="project-card__stats"><div><dt>Runtime</dt><dd>{production.runtime}</dd></div><div><dt>Health</dt><dd>{production.health}</dd></div><div><dt>Rollback</dt><dd>{production.rollback}</dd></div><div><dt>Main / prod</dt><dd>{shortSha(production.mainSha)} / {shortSha(production.productionSha)}</dd></div><div><dt>Blockers</dt><dd>{production.blockerCodes.length}</dd></div></dl>:<p className="section-empty-state">No sanitized production evidence is available in this snapshot.</p>}</div>:null}</article>;})}</div></section>
 <footer className="prototype-footer"><p>{live?"Live snapshot":"Fixture snapshot"}: {snapshotTimestamp(dashboard.generatedAt)} UTC</p><p>{liveState==="LIVE"?"Daily MVP · Confirmed decision actions · Deployment controls remain separate":live?"Last-known live evidence · Mutation controls disabled":"Daily MVP fallback · No live GitHub mutation · No deployment controls"}</p></footer></main><ActionConfirmationDialog target={pendingAction} pending={actionInFlight} onCancel={cancelDecisionAction} onConfirm={(reviewBody)=>void confirmDecisionAction(reviewBody)}/></div>;
}
