import { setTimeout as scheduleTimeout } from "node:timers";
import { URL } from "node:url";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

const liveDecision = { id: "browser-live-merge", projectId: "ops-workflows", workflowState: "WAITING", issueNumber: 421, issueTitle: "Browser regression fixture", prNumber: 999, prTitle: "Browser regression live decision", prUrl: "https://github.com/rozkalnsandris/ops-workflows/pull/999", ci: "PASS", review: "NOT_REQUIRED", deployImpact: "NO_DEPLOY", changedFiles: 2, expectedHeadSha: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", currentHeadSha: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", mainSha: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", reason: "Lightweight live evidence remains non-authoritative for GitHub writes.", lastReconciledAt: "2026-08-28T17:59:30Z", allowedActions: ["MERGE", "NEEDS_CHANGES", "LATER", "OPEN_PR"] };
function liveDashboard(ageMilliseconds = 0) { const observedAt = new Date(Date.now() - ageMilliseconds).toISOString(); return { generatedAt: observedAt, projects: [{ id: "ops-workflows", displayName: "Ops Workflows", repository: "rozkalnsandris/ops-workflows", enabled: true, productionAdapter: "none", status: "ATTENTION", openPullRequests: 1, openIssues: 1 }], decisions: [{ ...liveDecision, lastReconciledAt: observedAt }], productionVisibility: [], githubRateLimitHealth: { status: "HEALTHY", limit: 5000, remaining: 4500, used: 500, resetAt: new Date(Date.now() + 3600000).toISOString(), resource: "core", observedAt } }; }
function webhookObservability() { return { observedAt: new Date().toISOString(), status: "HEALTHY", staleAfterSeconds: 900, totalDeliveries: 7, nonTerminalCount: 0, deadLetteredCount: 0, staleEvidenceCount: 0, counts: { RECEIVED: 0, ENQUEUED: 0, PROCESSING: 0, RETRY_PENDING: 0, SUCCEEDED: 7, DEAD_LETTERED: 0 }, diagnostics: [], diagnosticsTruncated: false }; }
const authoritativeProjection = { kind: "PROJECTED", repository: "rozkalnsandris/ops-workflows", issueNumber: 421, pullNumber: 999, observedAt: "2026-08-28T18:00:01Z", commitStatusCoverage: "NOT_REQUESTED", policy: { coverage: "COMPLETE", sources: ["RULESET"], blockedReasons: [] }, decision: { ...liveDecision, workflowState: "MERGE_READY", reason: "Authoritative reconciliation permits bounded Needs changes eligibility.", lastReconciledAt: "2026-08-28T18:00:01Z", allowedActions: ["OPEN_PR"] } };
function sendJson(response, statusCode, payload) { response.statusCode = statusCode; response.setHeader("Content-Type", "application/json; charset=utf-8"); response.setHeader("Cache-Control", "no-store"); response.end(JSON.stringify(payload)); }
function scenarioFromReferer(request) { const referer = request.headers.referer; if (!referer) return null; try { return new URL(referer).searchParams.get("browserScenario"); } catch { return null; } }
async function readJsonBody(request) { let body = ""; for await (const chunk of request) { body += chunk.toString(); if (body.length > 12000) throw new Error("browser action request too large"); } return JSON.parse(body); }

export default defineConfig({ plugins: [react(), { name: "control-browser-regression-api", configureServer(server) { let staleArmed = false; let dashboardRequests = 0; let reconcileRequests = 0; let actionRequests = [];
  server.middlewares.use((request, response, next) => { const requestUrl = request.url ?? "/";
    if (requestUrl.startsWith("/__browser/arm-stale")) { staleArmed = true; response.statusCode = 204; response.end(); return; }
    if (requestUrl.startsWith("/__browser/reset")) { staleArmed = false; dashboardRequests = 0; reconcileRequests = 0; actionRequests = []; response.statusCode = 204; response.end(); return; }
    if (requestUrl.startsWith("/__browser/state")) { sendJson(response, 200, { dashboardRequests, reconcileRequests, actionRequests }); return; }
    if (requestUrl.startsWith("/api/health")) { sendJson(response, 200, { status: "ok", service: "rozkalns-control", phase: "phase-0", workerVersion: "browser-regression" }); return; }
    if (requestUrl.startsWith("/api/github/webhook-deliveries")) { const scenario = scenarioFromReferer(request); if (scenario === "observability-failure") { sendJson(response, 503, { error: "BROWSER_OBSERVABILITY_FAILURE" }); return; } sendJson(response, 200, webhookObservability()); return; }
    if (requestUrl.startsWith("/api/github/dashboard")) { dashboardRequests += 1; const scenario = scenarioFromReferer(request); if (scenario === "fixture") { sendJson(response, 503, { error: "LIVE_READ_DISABLED" }); return; } if (scenario === "stale" && staleArmed) { sendJson(response, 500, { error: "BROWSER_TEST_REFRESH_FAILURE" }); return; } sendJson(response, 200, liveDashboard(scenario === "aged" ? 300001 : 0)); return; }
    if (request.method === "GET" && requestUrl.startsWith("/api/github/reconcile?")) { reconcileRequests += 1; const url = new URL(requestUrl, "http://127.0.0.1:4173"); const exact = url.searchParams.get("repository") === "rozkalnsandris/ops-workflows" && url.searchParams.get("issue") === "421" && url.searchParams.get("pull") === "999" && [...url.searchParams.keys()].length === 3; sendJson(response, exact ? 200 : 400, exact ? authoritativeProjection : { error: "INVALID_BROWSER_RECONCILE_REQUEST" }); return; }
    if (request.method === "POST" && ["/api/github/merge", "/api/github/needs-changes", "/api/github/later"].includes(requestUrl)) { void readJsonBody(request).then((body) => { actionRequests.push({ path: requestUrl, body }); scheduleTimeout(() => sendJson(response, 200, { ok: true }), 120); }).catch(() => sendJson(response, 400, { error: "INVALID_BROWSER_REQUEST" })); return; }
    next();
  });
} }] });
