import {
  PHASE5_RPI5_SIGNER_HANDOFF_AUTHORITY_OWNER,
  PHASE5_RPI5_SIGNER_HANDOFF_CONTRACT,
  PHASE5_RPI5_SIGNER_HANDOFF_RECEIVER_LANE,
  PHASE5_RPI5_SIGNER_HANDOFF_RECEIVER_REPOSITORY,
  PHASE5_RPI5_SIGNER_HANDOFF_SCHEMA_VERSION,
  PHASE5_RPI5_SIGNER_HANDOFF_SOURCE_REPOSITORY,
  PHASE5_RPI5_SIGNER_HANDOFF_WORKER,
  type Phase5Rpi5SignerHandoffExpectedIdentity,
  type Phase5Rpi5SignerHandoffManifest,
} from "../src/shared/phase5-rpi5-signer-handoff.js";
import { RPI5_OBSERVATION_TRANSPORT_VERSION } from "../src/shared/rpi5-observation-transport.js";

export const PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_SOURCE_SHA = "a".repeat(40);
export const PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_DEPLOYMENT_ID =
  "11111111-1111-4111-8111-111111111111";
export const PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_VERSION_ID =
  "22222222-2222-4222-8222-222222222222";
export const PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_KEY_ID = "synthetic-rpi5-observation-key-v1";
export const PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_GENERATED_AT = "2026-09-10T17:00:00.000Z";
export const PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_NOW = "2026-09-10T17:04:59.000Z";

export const VALID_PHASE5_RPI5_SIGNER_HANDOFF = {
  schema_version: PHASE5_RPI5_SIGNER_HANDOFF_SCHEMA_VERSION,
  contract: PHASE5_RPI5_SIGNER_HANDOFF_CONTRACT,
  source_repository: PHASE5_RPI5_SIGNER_HANDOFF_SOURCE_REPOSITORY,
  control_source_sha: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_SOURCE_SHA,
  worker: PHASE5_RPI5_SIGNER_HANDOFF_WORKER,
  expected_worker: {
    deployment_id: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_DEPLOYMENT_ID,
    version_id: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_VERSION_ID,
    traffic_percent: 100,
    ingest_state: "PRESENT_TRUE",
  },
  key_id: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_KEY_ID,
  observation_contract_version: RPI5_OBSERVATION_TRANSPORT_VERSION,
  generated_at: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_GENERATED_AT,
  receiver: {
    repository: PHASE5_RPI5_SIGNER_HANDOFF_RECEIVER_REPOSITORY,
    lane: PHASE5_RPI5_SIGNER_HANDOFF_RECEIVER_LANE,
    authority_owner: PHASE5_RPI5_SIGNER_HANDOFF_AUTHORITY_OWNER,
  },
  authority: {
    evidence_only: true,
    grants_live_authority: false,
    grants_cross_repo_write: false,
    grants_rpi5_runtime_mutation: false,
  },
} as const satisfies Phase5Rpi5SignerHandoffManifest;

export const VALID_PHASE5_RPI5_SIGNER_HANDOFF_EXPECTED_IDENTITY = {
  control_source_sha: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_SOURCE_SHA,
  deployment_id: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_DEPLOYMENT_ID,
  version_id: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_VERSION_ID,
  key_id: PHASE5_RPI5_SIGNER_HANDOFF_FIXTURE_KEY_ID,
} as const satisfies Phase5Rpi5SignerHandoffExpectedIdentity;
