export const COMMON_BROWSER_SECURITY_HEADERS = {
  "Permissions-Policy": "camera=(), geolocation=(), microphone=(), payment=(), usb=()",
  "Referrer-Policy": "no-referrer",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
} as const;

export const API_CONTENT_SECURITY_POLICY =
  "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none'";

/** Apply the centralized policy to every response generated by the API Worker. */
export function applyApiResponseSecurityHeaders(response: Response): Response {
  for (const [name, value] of Object.entries(COMMON_BROWSER_SECURITY_HEADERS)) {
    response.headers.set(name, value);
  }
  response.headers.set("Content-Security-Policy", API_CONTENT_SECURITY_POLICY);
  return response;
}
