import type { ControlFixtureSet } from "./control-model.js";

const SHA_A = "1111111111111111111111111111111111111111";
const SHA_B = "2222222222222222222222222222222222222222";
const SHA_C = "3333333333333333333333333333333333333333";
const SHA_D = "4444444444444444444444444444444444444444";
const SHA_E = "5555555555555555555555555555555555555555";

export const controlFixtures: ControlFixtureSet = {
  generatedAt: "2026-08-10T08:48:00Z",
  projects: [
    {
      id: "hermes-deals",
      displayName: "Hermes Deals",
      repository: "rozkalnsandris/hermes-deals",
      enabled: true,
      productionAdapter: "rpi5",
      status: "ATTENTION",
      openPullRequests: 3,
      openIssues: 18,
    },
    {
      id: "hermes-tech",
      displayName: "Hermes Tech",
      repository: "rozkalnsandris/hermes-tech",
      enabled: true,
      productionAdapter: "rpi5",
      status: "HEALTHY",
      openPullRequests: 1,
      openIssues: 6,
    },
    {
      id: "rozkalns-cv",
      displayName: "Rozkalns CV",
      repository: "rozkalnsandris/rozkalns-cv",
      enabled: true,
      productionAdapter: "rpi5",
      status: "WAITING",
      openPullRequests: 1,
      openIssues: 4,
    },
    {
      id: "rpi5-main",
      displayName: "RPi5 Main",
      repository: "rozkalnsandris/RPi5_main",
      enabled: true,
      productionAdapter: "rpi5",
      status: "ATTENTION",
      openPullRequests: 2,
      openIssues: 11,
    },
    {
      id: "ops-workflows",
      displayName: "Ops Workflows",
      repository: "rozkalnsandris/ops-workflows",
      enabled: true,
      productionAdapter: "none",
      status: "HEALTHY",
      openPullRequests: 0,
      openIssues: 2,
    },
    {
      id: "profile",
      displayName: "GitHub Profile",
      repository: "rozkalnsandris/rozkalnsandris",
      enabled: true,
      productionAdapter: "none",
      status: "HEALTHY",
      openPullRequests: 0,
      openIssues: 0,
    },
  ],
  decisions: [
    {
      id: "fixture-deals-lidl",
      projectId: "hermes-deals",
      workflowState: "NEEDS_ANDRIS",
      issueNumber: 842,
      issueTitle: "Fixture: tighten Lidl leaflet evidence gate",
      prNumber: 847,
      prTitle: "Fixture: enforce Lidl evidence gate before promotion",
      ci: "PASS",
      review: "PASS",
      deployImpact: "NO_DEPLOY",
      changedFiles: 5,
      expectedHeadSha: SHA_A,
      currentHeadSha: SHA_A,
      mainSha: SHA_B,
      reason: "All required checks pass. Human merge authorization is the next permitted transition.",
      lastReconciledAt: "2026-08-10T08:47:30Z",
      allowedActions: ["MERGE", "NEEDS_CHANGES", "LATER", "OPEN_PR"],
    },
    {
      id: "fixture-rpi5-controller",
      projectId: "rpi5-main",
      workflowState: "NEEDS_ANDRIS",
      issueNumber: 151,
      issueTitle: "Fixture: controller rollout needs owner decision",
      prNumber: 154,
      prTitle: "Fixture: add guarded rollout evidence boundary",
      ci: "PASS",
      review: "PASS",
      deployImpact: "MANUAL_ROLLOUT_REQUIRED",
      changedFiles: 8,
      expectedHeadSha: SHA_C,
      currentHeadSha: SHA_C,
      mainSha: SHA_D,
      reason: "Source merge is safe, but the projected deploy class requires a separate manual rollout later.",
      lastReconciledAt: "2026-08-10T08:46:40Z",
      allowedActions: ["MERGE", "NEEDS_CHANGES", "LATER", "OPEN_PR"],
    },
    {
      id: "fixture-tech-working",
      projectId: "hermes-tech",
      workflowState: "WORKING",
      issueNumber: 108,
      issueTitle: "Fixture: audit metadata normalization",
      prNumber: null,
      prTitle: null,
      ci: "WAITING",
      review: "NOT_REQUIRED",
      deployImpact: "UNKNOWN",
      changedFiles: 0,
      expectedHeadSha: null,
      currentHeadSha: null,
      mainSha: SHA_E,
      reason: "Implementation is still in progress; no human action is currently required.",
      lastReconciledAt: "2026-08-10T08:45:00Z",
      allowedActions: [],
    },
    {
      id: "fixture-cv-waiting",
      projectId: "rozkalns-cv",
      workflowState: "WAITING",
      issueNumber: 149,
      issueTitle: "Fixture: wait for CI prerequisite evidence",
      prNumber: 150,
      prTitle: "Fixture: baseline-aware CV validation",
      ci: "RUNNING",
      review: "PENDING",
      deployImpact: "AUTO_DEPLOY_SAFE",
      changedFiles: 3,
      expectedHeadSha: SHA_B,
      currentHeadSha: SHA_B,
      mainSha: SHA_A,
      reason: "CI is still running. Control Center must wait rather than ask for premature approval.",
      lastReconciledAt: "2026-08-10T08:44:20Z",
      allowedActions: ["OPEN_PR"],
    },
    {
      id: "fixture-deals-ci-failed",
      projectId: "hermes-deals",
      workflowState: "CI_FAILED",
      issueNumber: 843,
      issueTitle: "Fixture: Netto comparison-family regression",
      prNumber: 848,
      prTitle: "Fixture: normalize comparison-family matching",
      ci: "FAIL",
      review: "PENDING",
      deployImpact: "NO_DEPLOY",
      changedFiles: 4,
      expectedHeadSha: SHA_D,
      currentHeadSha: SHA_D,
      mainSha: SHA_B,
      reason: "A required test failed. Merge is not an allowed action until CI returns to PASS.",
      lastReconciledAt: "2026-08-10T08:43:10Z",
      allowedActions: ["OPEN_PR"],
    },
    {
      id: "fixture-tech-merge-ready",
      projectId: "hermes-tech",
      workflowState: "MERGE_READY",
      issueNumber: 109,
      issueTitle: "Fixture: documentation-only cleanup",
      prNumber: 112,
      prTitle: "Fixture: clarify audit evidence contract",
      ci: "PASS",
      review: "PASS",
      deployImpact: "NO_DEPLOY",
      changedFiles: 2,
      expectedHeadSha: SHA_E,
      currentHeadSha: SHA_E,
      mainSha: SHA_C,
      reason: "The change is mechanically merge-ready but is not currently selected as a Needs Andris decision.",
      lastReconciledAt: "2026-08-10T08:42:00Z",
      allowedActions: ["OPEN_PR"],
    },
  ],
};
